### PR TITLE
To-Do List Testing

### PR DESCRIPTION
**Pull request by emiliocm9**
## JavaScript Testing with Jest

JavaScript functions and UI elements have been tested using Jest and Puppeteer:

- [x] Tests for correct implementation of tasks object.
- [x] Test for correct implementation of the project object.
- [x] Test for correct UI elements rendering.

> This PR is going to be reviewed by a TSE from Microverse, Inc.

### CODE REVIEW

**Comment by sumancrest0001** [comment]
**Status: Changes required :gear:
Hello @emiliocm9,**
It is a nice project and very functional. We need to make a couple of changes. Please consider the following points and make the necessary changes.
[Required] I couldn't find linter files. Please add and remove errors if any.
[Required] I couldn't run the test suites. I goT some errors related to babel. 
[Optional] You could have added logical methods to the respective classes. It makes testing easier.

**Please make the requested changes and submit the project for another review. If you have any questions, please message me on Slack Suman Shrestha.
Happy coding !!!**

**Comment by emiliocm9** [comment]
> **Status: Changes required ⚙️ Hello @emiliocm9,**
> It is a nice project and very functional. We need to make a couple of changes. Please consider the following points and make the necessary changes.
> [Required] I couldn't find linter files. Please add and remove errors if any.
> [Required] I couldn't run the test suites. I goT some errors related to babel.
> [Optional] You could have added logical methods to the respective classes. It makes testing easier.
> 
> **Please make the requested changes and submit the project for another review. If you have any questions, please message me on Slack Suman Shrestha. Happy coding !!!**

Thanks for the feedback. It was helpful to know I had to run Babel with yarn and fix the issues in my linter config files.
Warm regards!

**Review by kubilaycaglayan — APPROVED** [review]
#### Hello Team 👋
#### Status: Approved :green_circle: 

Great job! 👏👍 😊

:heavy_plus_sign:  Now the test suites are running without any problem.
:heavy_plus_sign:  And you have your proper linter files.

Good luck with your next project!
With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

**Comment by emiliocm9** [comment]
> #### Hello Team 👋
> #### Status: Approved 🟢
> Great job! 👏👍 😊
> 
> ➕ Now the test suites are running without any problem.
> ➕ And you have your proper linter files.
> 
> Good luck with your next project!
> With all my respect 🙏
> 
> > Kubilay Caglayan | Technical Support Engineer

Thank you very much!
Have a great day

**Pull request merged**
